### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 2to2filuk** [cocaine666/valorant-cheat#1]
why am i getting this error? 

"fatal error: winternl.h: No such file or directory"

btw thanks for sharing it!

**Comment by cocaine666** [comment]
If you have the Windows SDK, try adding includes in project options.

**Comment by 2to2filuk** [comment]
> If you have the Windows SDK, try adding includes in project options.

when i already installed it will it fix the error?

**Comment by cocaine666** [comment]
Probably yes.

**Comment by 2to2filuk** [comment]
> Probably yes.

i already installed windows sdk but still have the issue,  btw im using Visual Studio Code

can you add me on discord please? Repolyoo#1874

**Comment by cocaine666** [comment]
Don't use Visual Studio Code.  Use Visual Studio Community, create a project, add the files to it and compile it in x64.

**Comment by 2to2filuk** [comment]
do you have discord, to ask some questions about something :/
