### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by 2to2filuk** [cocaine666/valorant-cheat#2]
will i compile it with x86 or x64 debug or release? because the triggerbot is so slow :/

**Comment by caqlayan** [comment]
> will i compile it with x86 or x64 debug or release? because the triggerbot is so slow :/

Hi. I couldn't compile it. Could you help me ?

**Comment by cocaine666** [comment]
Please, learn a bit about programming. Compile it in x64.

**Comment by caqlayan** [comment]
> Please, learn a bit about programming. Compile it in x64.

I tried but i keep getting errors. Which program should i compile with?

**Comment by cocaine666** [comment]
Visual Studio Community. And triggerbot is slow because your settings are bad. Try these X: 3 Y: 7 D: 0 R: 2
