### ISSUE TITLE
how do you ya know set up up 

### ISSUE THREAD

**Issue by erh465t54thh54** [cocaine666/valorant-cheat#3]
all you said was download the files and logictec thingy now what do i put it as macro and witch macro do i have to use somthing else or is this all i need? i have no idea what this stuff means i just wanna see if it works so i can use it and do good in a game for once

**Comment by kmalbasic** [comment]
First, this isn't a macro. You need to compile it and have Logitech GHUB running in the background.

**Comment by erh465t54thh54** [comment]
> First, this isn't a macro. You need to compile it and have Logitech GHUB running in the background.

What?

**Comment by kmalbasic** [comment]
It is not a macro, it just utilizes the GHUB driver for moving and clicking the mouse. It's an exe file.
