### ISSUE TITLE
ghub

### ISSUE THREAD

**Issue by NotSwxg** [cocaine666/valorant-cheat#5]
it says it failed to open ghub macro driver, i reinstalled ghub but still not working.

**Comment by kmalbasic** [comment]
Modify numbers 0002 to 0001, 0003... to 0009 and it will work [Line you need to modify](https://github.com/cocaine666/valorant-cheat/blob/9655ea7cd94a53d88db1b62f191aa4d751c662a2/mouse.c#L51)
